// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pravopisly.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PravopislyComms_SendText_FullMethodName = "/pravopisly.PravopislyComms/SendText"
)

// PravopislyCommsClient is the client API for PravopislyComms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PravopislyCommsClient interface {
	SendText(ctx context.Context, in *SendToModel, opts ...grpc.CallOption) (*ModelReply, error)
}

type pravopislyCommsClient struct {
	cc grpc.ClientConnInterface
}

func NewPravopislyCommsClient(cc grpc.ClientConnInterface) PravopislyCommsClient {
	return &pravopislyCommsClient{cc}
}

func (c *pravopislyCommsClient) SendText(ctx context.Context, in *SendToModel, opts ...grpc.CallOption) (*ModelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelReply)
	err := c.cc.Invoke(ctx, PravopislyComms_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PravopislyCommsServer is the server API for PravopislyComms service.
// All implementations must embed UnimplementedPravopislyCommsServer
// for forward compatibility.
type PravopislyCommsServer interface {
	SendText(context.Context, *SendToModel) (*ModelReply, error)
	mustEmbedUnimplementedPravopislyCommsServer()
}

// UnimplementedPravopislyCommsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPravopislyCommsServer struct{}

func (UnimplementedPravopislyCommsServer) SendText(context.Context, *SendToModel) (*ModelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedPravopislyCommsServer) mustEmbedUnimplementedPravopislyCommsServer() {}
func (UnimplementedPravopislyCommsServer) testEmbeddedByValue()                         {}

// UnsafePravopislyCommsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PravopislyCommsServer will
// result in compilation errors.
type UnsafePravopislyCommsServer interface {
	mustEmbedUnimplementedPravopislyCommsServer()
}

func RegisterPravopislyCommsServer(s grpc.ServiceRegistrar, srv PravopislyCommsServer) {
	// If the following call panics, it indicates UnimplementedPravopislyCommsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PravopislyComms_ServiceDesc, srv)
}

func _PravopislyComms_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PravopislyCommsServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PravopislyComms_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PravopislyCommsServer).SendText(ctx, req.(*SendToModel))
	}
	return interceptor(ctx, in, info, handler)
}

// PravopislyComms_ServiceDesc is the grpc.ServiceDesc for PravopislyComms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PravopislyComms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pravopisly.PravopislyComms",
	HandlerType: (*PravopislyCommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendText",
			Handler:    _PravopislyComms_SendText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pravopisly.proto",
}
