// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pravopisly.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendToModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToModel) Reset() {
	*x = SendToModel{}
	mi := &file_pravopisly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToModel) ProtoMessage() {}

func (x *SendToModel) ProtoReflect() protoreflect.Message {
	mi := &file_pravopisly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToModel.ProtoReflect.Descriptor instead.
func (*SendToModel) Descriptor() ([]byte, []int) {
	return file_pravopisly_proto_rawDescGZIP(), []int{0}
}

func (x *SendToModel) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ModelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommaProbs    []float32              `protobuf:"fixed32,1,rep,packed,name=comma_probs,json=commaProbs,proto3" json:"comma_probs,omitempty"`
	GrammarProbs  []float32              `protobuf:"fixed32,2,rep,packed,name=grammar_probs,json=grammarProbs,proto3" json:"grammar_probs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelReply) Reset() {
	*x = ModelReply{}
	mi := &file_pravopisly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelReply) ProtoMessage() {}

func (x *ModelReply) ProtoReflect() protoreflect.Message {
	mi := &file_pravopisly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelReply.ProtoReflect.Descriptor instead.
func (*ModelReply) Descriptor() ([]byte, []int) {
	return file_pravopisly_proto_rawDescGZIP(), []int{1}
}

func (x *ModelReply) GetCommaProbs() []float32 {
	if x != nil {
		return x.CommaProbs
	}
	return nil
}

func (x *ModelReply) GetGrammarProbs() []float32 {
	if x != nil {
		return x.GrammarProbs
	}
	return nil
}

var File_pravopisly_proto protoreflect.FileDescriptor

const file_pravopisly_proto_rawDesc = "" +
	"\n" +
	"\x10pravopisly.proto\x12\n" +
	"Pravopisly\"!\n" +
	"\vSendToModel\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\n" +
	"ModelReply\x12\x1f\n" +
	"\vcomma_probs\x18\x01 \x03(\x02R\n" +
	"commaProbs\x12#\n" +
	"\rgrammar_probs\x18\x02 \x03(\x02R\fgrammarProbs2P\n" +
	"\x0fPravopislyComms\x12=\n" +
	"\bSendText\x12\x17.Pravopisly.SendToModel\x1a\x16.Pravopisly.ModelReply\"\x00B'Z%github.com/YoDobchev/pravopisly/be/pbb\x06proto3"

var (
	file_pravopisly_proto_rawDescOnce sync.Once
	file_pravopisly_proto_rawDescData []byte
)

func file_pravopisly_proto_rawDescGZIP() []byte {
	file_pravopisly_proto_rawDescOnce.Do(func() {
		file_pravopisly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pravopisly_proto_rawDesc), len(file_pravopisly_proto_rawDesc)))
	})
	return file_pravopisly_proto_rawDescData
}

var file_pravopisly_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pravopisly_proto_goTypes = []any{
	(*SendToModel)(nil), // 0: Pravopisly.SendToModel
	(*ModelReply)(nil),  // 1: Pravopisly.ModelReply
}
var file_pravopisly_proto_depIdxs = []int32{
	0, // 0: Pravopisly.PravopislyComms.SendText:input_type -> Pravopisly.SendToModel
	1, // 1: Pravopisly.PravopislyComms.SendText:output_type -> Pravopisly.ModelReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pravopisly_proto_init() }
func file_pravopisly_proto_init() {
	if File_pravopisly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pravopisly_proto_rawDesc), len(file_pravopisly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pravopisly_proto_goTypes,
		DependencyIndexes: file_pravopisly_proto_depIdxs,
		MessageInfos:      file_pravopisly_proto_msgTypes,
	}.Build()
	File_pravopisly_proto = out.File
	file_pravopisly_proto_goTypes = nil
	file_pravopisly_proto_depIdxs = nil
}
