# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pravopisly.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pravopisly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pravopisly.proto\x12\nPravopisly\"\x1b\n\x0bSendToModel\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\nModelReply\x12\x13\n\x0b\x63omma_probs\x18\x01 \x03(\x02\x12\x15\n\rgrammar_probs\x18\x02 \x03(\x02\x32P\n\x0fPravopislyComms\x12=\n\x08SendText\x12\x17.Pravopisly.SendToModel\x1a\x16.Pravopisly.ModelReply\"\x00\x42\'Z%github.com/YoDobchev/pravopisly/be/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pravopisly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/YoDobchev/pravopisly/be/pb'
  _globals['_SENDTOMODEL']._serialized_start=32
  _globals['_SENDTOMODEL']._serialized_end=59
  _globals['_MODELREPLY']._serialized_start=61
  _globals['_MODELREPLY']._serialized_end=117
  _globals['_PRAVOPISLYCOMMS']._serialized_start=119
  _globals['_PRAVOPISLYCOMMS']._serialized_end=199
# @@protoc_insertion_point(module_scope)
